apiVersion: hydrolix.io/v1
kind: Project
metadata:
  name: akamai
  namespace: default
spec:
  name: akamai
  description: This is an example project created via ArgoCD
  settings:
    featureFlag: true
    maxRetries: 16
